CREATE TABLE DEPARTMENTS
(DEPT_NO VARCHAR(4) NOT NULL,
DEPT_NAME VARCHAR(40) NOT NULL,	
PRIMARY KEY (DEPT_NO));

CREATE TABLE DEPT_EMP
(EMP_NO INT NOT NULL,
 DEPT_NO VARCHAR(4) NOT NULL,
PRIMARY KEY (EMP_NO),
FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO))

CREATE TABLE DEPT_MANAGER
(DEPT_NO VARCHAR(4) NOT NULL
EMP_NO INT NOT NULL,				
PRIMARY KEY (DEPT_NO),
FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO));


CREATE TABLE EMPLOYEES(EMP_NO INT NOT  NULL,
EMP_TITLE_ID VARCHAR(5) NOT NULL,
BIRTH_DATE DATE NOT  NULL,
FIRST_NAME VARCHAR(40) NOT NULL,
LAST_NAME VARCHAR(40) NOT NULL,
SEX VARCHAR(1) NOT NULL,
HIRE_DATE DATE NOT NULL,
PRIMARY KEY (EMP_NO),
FOREIGN KEY (EMP_TITLE_ID) REFERENCES TITLES (TITLE_ID));


CREATE TABLE SALARIES
(EMP_NO INT NOT NULL,		
SALARY INT NOT NULL,
PRIMARY KEY (EMP_NO),
FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO));


CREATE TABLE TITLES
(TITLE_ID VARCHAR(5) NOT NULL,
TITLE VARCHAR(50) NOT NULL,
PRIMARY KEY (TITLE_ID));
